INSERT INTO posts (user_id, image_url, caption, likes_count, comments_count, created_at) VALUES
('@madsbas', 'http://localhost:8080/ViewWorld/images/post1.jpg', 'Enjoying the sunset!', 120, 15, NOW()),
('@view', 'http://localhost:8080/ViewWorld/images/post2.jpg', 'Adventure awaits.', 250, 32, NOW()),
('@john_doe', 'http://localhost:8080/ViewWorld/images/post3.jpg', 'Nature is calling.', 85, 10, NOW()),
('@jane_smith', 'http://localhost:8080/ViewWorld/images/post4.jpg', 'Captured a beautiful moment.', 320, 45, NOW()),
('@cowboydan', 'http://localhost:8080/ViewWorld/images/post5.jpg', 'The cowboy life.', 75, 18, NOW()),
('@techguy', 'http://localhost:8080/ViewWorld/images/post6.jpg', 'Trying out new gadgets.', 145, 27, NOW()),
('@foodiequeen', 'http://localhost:8080/ViewWorld/images/post7.jpg', 'Best dessert ever!', 190, 60, NOW()),
('@traveler99', 'http://localhost:8080/ViewWorld/images/post8.jpg', 'Exploring new cities.', 290, 80, NOW()),
('@fitness_fanatic', 'http://localhost:8080/ViewWorld/images/post9.jpg', 'Workout time!', 210, 35, NOW()),
('@bookworm', 'http://localhost:8080/ViewWorld/images/post10.jpg', 'Reading a classic novel.', 85, 12, NOW()),
('@madsbas', 'http://localhost:8080/ViewWorld/images/post11.jpg', 'Coffee time.', 95, 20, NOW()),
('@view', 'http://localhost:8080/ViewWorld/images/post12.jpg', 'Breathtaking view!', 275, 50, NOW()),
('@john_doe', 'http://localhost:8080/ViewWorld/images/post13.jpg', 'Lonely road.', 65, 8, NOW()),
('@jane_smith', 'http://localhost:8080/ViewWorld/images/post14.jpg', 'Artistic vibes.', 340, 55, NOW()),
('@cowboydan', 'http://localhost:8080/ViewWorld/images/post15.jpg', 'Another day on the ranch.', 100, 20, NOW()),
('@techguy', 'http://localhost:8080/ViewWorld/images/post16.jpg', 'Coding all night!', 210, 40, NOW()),
('@foodiequeen', 'http://localhost:8080/ViewWorld/images/post17.jpg', 'Mouth-watering food!', 270, 70, NOW()),
('@traveler99', 'http://localhost:8080/ViewWorld/images/post18.jpg', 'Wanderlust vibes.', 310, 85, NOW()),
('@fitness_fanatic', 'http://localhost:8080/ViewWorld/images/post19.jpg', 'Fitness journey.', 250, 35, NOW()),
('@bookworm', 'http://localhost:8080/ViewWorld/images/post20.jpg', 'So many books, so little time.', 120, 18, NOW()),
('@madsbas', 'http://localhost:8080/ViewWorld/images/post21.jpg', 'Early morning coffee.', 75, 12, NOW()),
('@view', 'http://localhost:8080/ViewWorld/images/post22.jpg', 'Exploring the hills.', 300, 48, NOW()),
('@john_doe', 'http://localhost:8080/ViewWorld/images/post23.jpg', 'Peace and quiet.', 50, 7, NOW()),
('@jane_smith', 'http://localhost:8080/ViewWorld/images/post24.jpg', 'Creative mood.', 400, 65, NOW()),
('@cowboydan', 'http://localhost:8080/ViewWorld/images/post25.jpg', 'Sunset on the ranch.', 110, 22, NOW()),
('@techguy', 'http://localhost:8080/ViewWorld/images/post26.jpg', 'Tech discoveries.', 240, 35, NOW()),
('@foodiequeen', 'http://localhost:8080/ViewWorld/images/post27.jpg', 'Gourmet meal tonight!', 305, 75, NOW()),
('@traveler99', 'http://localhost:8080/ViewWorld/images/post28.jpg', 'Into the unknown.', 345, 90, NOW()),
('@fitness_fanatic', 'http://localhost:8080/ViewWorld/images/post29.jpg', 'Healthy lifestyle.', 220, 32, NOW()),
('@bookworm', 'http://localhost:8080/ViewWorld/images/post30.jpg', 'New book release!', 150, 25, NOW());
